"""Generate private, sourceable MVP operation configuration templates.

The template centralizes design/product inputs, provider credentials, local
workspace paths, and S3 publication settings without making the existing CLI
commands depend on a new configuration parser.
"""

from __future__ import annotations

import os
import re
import shlex
import tempfile
from datetime import date
from pathlib import Path


class OperationConfigError(ValueError):
    """Raised when an operation configuration cannot be created safely."""


_ID_PATTERN = re.compile(r"[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")


def _identifier(value: str, label: str) -> str:
    if _ID_PATTERN.fullmatch(value) is None:
        raise OperationConfigError(
            f"{label} must use lowercase letters, numbers, and single hyphens: {value!r}"
        )
    return value


def _export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def _template(
    *,
    output: Path,
    project_root: Path,
    design_id: str,
    product_profile_id: str,
) -> str:
    release_id = f"{date.today().isoformat()}.001"
    literal_values = [
        ("PAWMARVEL_CONFIG_FILE", str(output)),
        ("PAWMARVEL_PROJECT", str(project_root)),
        ("PAWMARVEL_DESIGN_ID", design_id),
        ("PAWMARVEL_PRODUCT_PROFILE_ID", product_profile_id),
    ]
    lines = [
        "# PawMarvel private MVP operation configuration.",
        "# Generated by: pawmarvel-author init-config",
        f"# Edit values below, then run: source {shlex.quote(str(output))}",
        "# This file may contain secrets. Keep it under ignored work/ and mode 0600.",
        "# Empty provider keys are allowed when that provider/backend is not used.",
        "",
        "# Identity and repository root",
        *[_export(name, value) for name, value in literal_values],
        "",
        "# Design/product inputs",
        'export PAWMARVEL_DESIGN_INPUT="$PAWMARVEL_PROJECT/work/design-inputs/$PAWMARVEL_DESIGN_ID"',
        'export PAWMARVEL_SAMPLE="$PAWMARVEL_DESIGN_INPUT/reference-design.png"',
        'export PAWMARVEL_ART_PROMPT="$PAWMARVEL_DESIGN_INPUT/art-template-gpt.md"',
        'export PAWMARVEL_PET_PROMPT="$PAWMARVEL_DESIGN_INPUT/pet-transform-gpt.md"',
        'export PAWMARVEL_ART_PROMPT_GEMINI="$PAWMARVEL_DESIGN_INPUT/art-template-gemini.md"',
        'export PAWMARVEL_PET_PROMPT_GEMINI="$PAWMARVEL_DESIGN_INPUT/pet-transform-gemini.md"',
        'export PAWMARVEL_PET="$PAWMARVEL_PROJECT/examples/pet-inputs/sausage-dog-puppy.png"',
        'export PAWMARVEL_PROFILE="$PAWMARVEL_PROJECT/profiles/$PAWMARVEL_PRODUCT_PROFILE_ID.json"',
        'export PAWMARVEL_FONT_CATALOG="$PAWMARVEL_PROJECT/assets/fonts"',
        'if test -f "$PAWMARVEL_DESIGN_INPUT/font-reference.json"; then export PAWMARVEL_FONT_REFERENCE="$PAWMARVEL_DESIGN_INPUT/font-reference.json"; else export PAWMARVEL_FONT_REFERENCE=""; fi',
        'if test -f "$PAWMARVEL_DESIGN_INPUT/layout-reference.json"; then export PAWMARVEL_LAYOUT_REFERENCE="$PAWMARVEL_DESIGN_INPUT/layout-reference.json"; else export PAWMARVEL_LAYOUT_REFERENCE=""; fi',
        'export PAWMARVEL_EVALUATION_PROTOCOL="$PAWMARVEL_PROJECT/examples/authoring/evaluation-protocols/mvp-image-v1.json"',
        'export PAWMARVEL_FIXTURE_SET="$PAWMARVEL_PROJECT/examples/authoring/fixture-sets/mvp-pets-v1/fixture-set.json"',
        "export PAWMARVEL_PET_NAME='SAUSAGE'",
        "export PAWMARVEL_PET_NAME_MAX_LENGTH='12'",
        "",
        "# Default experiment configuration",
        "export PAWMARVEL_ART_PROVIDER='openai'",
        "export PAWMARVEL_ART_MODEL='gpt-image-2'",
        "export PAWMARVEL_ART_QUALITY='high'",
        "export PAWMARVEL_PET_PROVIDER='openai'",
        "export PAWMARVEL_PET_MODEL='gpt-image-2'",
        "export PAWMARVEL_PET_QUALITY='low'",
        "export PAWMARVEL_UPSCALE_BACKEND='deterministic'",
        "",
        "# Provider credentials; paste only the keys needed by this iteration",
        "export OPENAI_API_KEY=''",
        "export GEMINI_API_KEY=''",
        "export BRIA_API_TOKEN=''",
        "",
        "# Local ignored workspaces",
        'export PAWMARVEL_AUTHORING_ROOT="$PAWMARVEL_PROJECT/work/authoring"',
        'export PAWMARVEL_AUTHORING_PRODUCT="$PAWMARVEL_AUTHORING_ROOT/$PAWMARVEL_DESIGN_ID/$PAWMARVEL_PRODUCT_PROFILE_ID"',
        'export PAWMARVEL_EXCHANGE="$PAWMARVEL_PROJECT/work/exchange"',
        'export PAWMARVEL_PROMPT_CANDIDATES="$PAWMARVEL_PROJECT/work/prompt-candidates/$PAWMARVEL_DESIGN_ID"',
        "",
        "# S3 publication; AWS_PROFILE is preferred over access keys in this file",
        "export AWS_PROFILE='default'",
        "export AWS_REGION='us-west-2'",
        "export PAWMARVEL_S3_BUCKET=''",
        "export PAWMARVEL_S3_PREFIX='mvp'",
        "case \"$PAWMARVEL_S3_PREFIX\" in",
        "  /*|*/) printf '%s\\n' 'PAWMARVEL_S3_PREFIX must not have a leading or trailing slash' >&2; return 2 2>/dev/null || exit 2 ;;",
        "esac",
        "# Target release to create with build-release; this does not discover an existing catalog.",
        _export("PAWMARVEL_RELEASE_ID", release_id),
        'export PAWMARVEL_RELEASE="$PAWMARVEL_EXCHANGE/releases/$PAWMARVEL_RELEASE_ID/catalog.json"',
        'export PAWMARVEL_S3_CATALOG="s3://$PAWMARVEL_S3_BUCKET/$PAWMARVEL_S3_PREFIX/releases/$PAWMARVEL_RELEASE_ID/catalog.json"',
        "",
    ]
    return "\n".join(lines)


def write_operation_config(
    *,
    output: Path,
    project_root: Path,
    design_id: str,
    product_profile_id: str,
    force: bool = False,
) -> Path:
    """Create a mode-0600 shell configuration without silently replacing secrets."""
    target = output.expanduser().resolve()
    project = project_root.expanduser().resolve()
    _identifier(design_id, "design ID")
    _identifier(product_profile_id, "product profile ID")
    if not project.is_dir():
        raise OperationConfigError(f"project root is not a directory: {project}")
    work_root = (project / "work").resolve()
    try:
        target.relative_to(work_root)
    except ValueError as exc:
        raise OperationConfigError(
            f"operation config must be under the ignored work directory: {work_root}; "
            f"actual={target}"
        ) from exc
    if target.exists() and not force:
        raise OperationConfigError(
            f"operation config already exists: {target}; use --force to replace it"
        )
    (project / "work" / "design-inputs" / design_id).mkdir(
        parents=True, exist_ok=True
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}-", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(
                _template(
                    output=target,
                    project_root=project,
                    design_id=design_id,
                    product_profile_id=product_profile_id,
                )
            )
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
        target.chmod(0o600)
    finally:
        temporary.unlink(missing_ok=True)
    return target
