"""Generate shared and design-scoped private operation configuration files."""

from __future__ import annotations

import os
import re
import shlex
import tempfile
from datetime import date
from pathlib import Path

from .generation_contract import validate_generation_quality


class OperationConfigError(ValueError):
    """Raised when an operation configuration cannot be created safely."""


_ID_PATTERN = re.compile(r"[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
ART_TEMPLATE_MODES = ("generated", "empty-canvas")
NAME_MODES = ("layout-text", "embedded-in-pet", "none")
IMAGE_PROVIDERS = ("openai", "gemini")
UPSCALE_BACKENDS = ("deterministic", "bria")
DEFAULT_MODELS = {
    "openai": "gpt-image-2.5-sunburst",
    "gemini": "gemini-3.1-flash-image",
}


def _identifier(value: str, label: str) -> str:
    if _ID_PATTERN.fullmatch(value) is None:
        raise OperationConfigError(
            f"{label} must use lowercase letters, numbers, and single hyphens: {value!r}"
        )
    return value


def _version_label(version_number: int) -> str:
    if isinstance(version_number, bool) or not 1 <= version_number <= 999999:
        raise OperationConfigError("version number must be between 1 and 999999")
    return f"v{version_number:02d}"


def _export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def _design_template(
    *,
    output: Path,
    project_root: Path,
    design_id: str,
    product_profile_id: str,
    art_template_mode: str,
    art_provider: str,
    art_model: str,
    art_quality: str,
    pet_provider: str,
    pet_model: str,
    pet_quality: str,
    name_mode: str,
    pet_name: str,
    pet_name_max_length: int,
    upscale_backend: str,
) -> str:
    release_id = f"{date.today().isoformat()}.001"
    literal_values = [
        ("PAWMARVEL_CONFIG_FILE", str(output)),
        ("PAWMARVEL_PROJECT", str(project_root)),
        ("PAWMARVEL_DESIGN_ID", design_id),
        ("PAWMARVEL_PRODUCT_PROFILE_ID", product_profile_id),
    ]
    lines = [
        "# PawMarvel private MVP operation configuration.",
        "# Generated by: pawmarvel-author init-config",
        f"# Edit values below, then run: source {shlex.quote(str(output))}",
        "# Source pawmarvel-shared.env first. This file contains no credentials.",
        "",
        "# Identity and repository root",
        *[_export(name, value) for name, value in literal_values],
        "",
        "# Design/product inputs",
        'export PAWMARVEL_DESIGN_INPUT="$PAWMARVEL_PROJECT/work/design-inputs/$PAWMARVEL_DESIGN_ID"',
        'export PAWMARVEL_SAMPLE="$PAWMARVEL_DESIGN_INPUT/reference-design.png"',
        'export PAWMARVEL_ART_PROMPT_GPT="$PAWMARVEL_DESIGN_INPUT/art-template-gpt.md"',
        'export PAWMARVEL_PET_PROMPT_GPT="$PAWMARVEL_DESIGN_INPUT/pet-transform-gpt.md"',
        'export PAWMARVEL_ART_PROMPT_GEMINI="$PAWMARVEL_DESIGN_INPUT/art-template-gemini.md"',
        'export PAWMARVEL_PET_PROMPT_GEMINI="$PAWMARVEL_DESIGN_INPUT/pet-transform-gemini.md"',
        'export PAWMARVEL_PET="$PAWMARVEL_PROJECT/examples/pet-inputs/sausage-dog-puppy.png"',
        'export PAWMARVEL_PROFILE="$PAWMARVEL_PROJECT/profiles/$PAWMARVEL_PRODUCT_PROFILE_ID.json"',
        'export PAWMARVEL_FONT_CATALOG="$PAWMARVEL_PROJECT/assets/fonts"',
        'if test -f "$PAWMARVEL_DESIGN_INPUT/font-reference.json"; then export PAWMARVEL_FONT_REFERENCE="$PAWMARVEL_DESIGN_INPUT/font-reference.json"; else export PAWMARVEL_FONT_REFERENCE=""; fi',
        'if test -f "$PAWMARVEL_DESIGN_INPUT/layout-reference.json"; then export PAWMARVEL_LAYOUT_REFERENCE="$PAWMARVEL_DESIGN_INPUT/layout-reference.json"; else export PAWMARVEL_LAYOUT_REFERENCE=""; fi',
        'export PAWMARVEL_EVALUATION_PROTOCOL="$PAWMARVEL_PROJECT/examples/authoring/evaluation-protocols/mvp-image-v1.json"',
        'export PAWMARVEL_SMOKE_FIXTURE_SET="$PAWMARVEL_PROJECT/examples/authoring/fixture-sets/mvp-pets-smoke-v1/fixture-set.json"',
        'export PAWMARVEL_RELEASE_FIXTURE_SET="$PAWMARVEL_PROJECT/examples/authoring/fixture-sets/mvp-pets-v1/fixture-set.json"',
        _export("PAWMARVEL_PET_NAME", pet_name),
        _export("PAWMARVEL_PET_NAME_MAX_LENGTH", str(pet_name_max_length)),
        "",
        "# Default experiment configuration",
        "# Production default: gpt-image-2.5-sunburst. Use gpt-image-2.5-flare for a speed experiment.",
        "# GPT Image 2.5 also permits xhigh/max; keep explicit quality fixed during comparisons.",
        "# Name mode: layout-text | embedded-in-pet | none",
        _export("PAWMARVEL_NAME_MODE", name_mode),
        "# Art template mode: generated | empty-canvas",
        _export("PAWMARVEL_ART_TEMPLATE_MODE", art_template_mode),
        _export("PAWMARVEL_ART_PROVIDER", art_provider),
        _export("PAWMARVEL_ART_MODEL", art_model),
        _export("PAWMARVEL_ART_QUALITY", art_quality),
        _export("PAWMARVEL_PET_PROVIDER", pet_provider),
        _export("PAWMARVEL_PET_MODEL", pet_model),
        _export("PAWMARVEL_PET_QUALITY", pet_quality),
        _export("PAWMARVEL_UPSCALE_BACKEND", upscale_backend),
        "case \"$PAWMARVEL_ART_PROVIDER\" in",
        '  openai) export PAWMARVEL_ART_PROMPT="$PAWMARVEL_ART_PROMPT_GPT" ;;',
        '  gemini) export PAWMARVEL_ART_PROMPT="$PAWMARVEL_ART_PROMPT_GEMINI" ;;',
        "  *) printf 'unsupported PAWMARVEL_ART_PROVIDER: %s\\n' \"$PAWMARVEL_ART_PROVIDER\" >&2; return 2 2>/dev/null || exit 2 ;;",
        "esac",
        "case \"$PAWMARVEL_PET_PROVIDER\" in",
        '  openai) export PAWMARVEL_PET_PROMPT="$PAWMARVEL_PET_PROMPT_GPT" ;;',
        '  gemini) export PAWMARVEL_PET_PROMPT="$PAWMARVEL_PET_PROMPT_GEMINI" ;;',
        "  *) printf 'unsupported PAWMARVEL_PET_PROVIDER: %s\\n' \"$PAWMARVEL_PET_PROVIDER\" >&2; return 2 2>/dev/null || exit 2 ;;",
        "esac",
        "",
        "# Local ignored workspaces",
        'export PAWMARVEL_AUTHORING_ROOT="$PAWMARVEL_PROJECT/work/authoring"',
        'export PAWMARVEL_AUTHORING_PRODUCT="$PAWMARVEL_AUTHORING_ROOT/$PAWMARVEL_DESIGN_ID/$PAWMARVEL_PRODUCT_PROFILE_ID"',
        'export PAWMARVEL_BENCHMARK_SELECTION_ROOT="$PAWMARVEL_AUTHORING_PRODUCT/benchmark-selections"',
        'export PAWMARVEL_EXCHANGE="$PAWMARVEL_PROJECT/work/exchange"',
        'export PAWMARVEL_PROMPT_CANDIDATES="$PAWMARVEL_PROJECT/work/prompt-candidates/$PAWMARVEL_DESIGN_ID"',
        "",
        "# Target release to create with build-release; this does not discover an existing catalog.",
        _export("PAWMARVEL_RELEASE_ID", release_id),
        'export PAWMARVEL_RELEASE="$PAWMARVEL_EXCHANGE/releases/$PAWMARVEL_RELEASE_ID/catalog.json"',
        "",
    ]
    return "\n".join(lines)


def _shared_template(*, output: Path) -> str:
    lines = [
        "# PawMarvel reusable private provider and publication configuration.",
        "# Generated by: pawmarvel-author init-shared-config",
        f"# Edit values below, then run: source {shlex.quote(str(output))}",
        "# This file contains secrets. Keep it under ignored work/ and mode 0600.",
        "# Empty provider keys are allowed when that provider/backend is not used.",
        "",
        _export("PAWMARVEL_SHARED_CONFIG_FILE", str(output)),
        "",
        "# Provider credentials",
        "export OPENAI_API_KEY=''",
        "export GEMINI_API_KEY=''",
        "export BRIA_API_TOKEN=''",
        "",
        "# S3 publication; prefer an AWS profile or SSO over access keys",
        "export AWS_PROFILE='default'",
        "export AWS_REGION='us-west-2'",
        "export PAWMARVEL_S3_BUCKET=''",
        "export PAWMARVEL_S3_PREFIX='mvp'",
        "case \"$PAWMARVEL_S3_PREFIX\" in",
        "  /*|*/) printf '%s\\n' 'PAWMARVEL_S3_PREFIX must not have a leading or trailing slash' >&2; return 2 2>/dev/null || exit 2 ;;",
        "esac",
        "",
    ]
    return "\n".join(lines)


def _write_private_config(target: Path, contents: str, *, force: bool) -> Path:
    if target.exists() and not force:
        raise OperationConfigError(
            f"operation config already exists: {target}; use --force to replace it"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}-", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(contents)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
        target.chmod(0o600)
    finally:
        temporary.unlink(missing_ok=True)
    return target


def write_shared_config(
    *, project_root: Path, force: bool = False
) -> Path:
    """Create the reusable provider/AWS configuration once per workspace."""
    project = project_root.expanduser().resolve()
    if not project.is_dir():
        raise OperationConfigError(f"project root is not a directory: {project}")
    target = (project / "work" / "configs" / "pawmarvel-shared.env").resolve()
    return _write_private_config(
        target,
        _shared_template(output=target),
        force=force,
    )


def write_operation_config(
    *,
    project_root: Path,
    design_id: str,
    product_profile_id: str,
    version_number: int = 1,
    art_template_mode: str = "generated",
    art_provider: str = "openai",
    art_model: str | None = None,
    art_quality: str = "high",
    pet_provider: str = "openai",
    pet_model: str | None = None,
    pet_quality: str = "low",
    name_mode: str = "layout-text",
    pet_name: str = "SAUSAGE",
    pet_name_max_length: int = 12,
    upscale_backend: str = "deterministic",
    force: bool = False,
) -> Path:
    """Create a mode-0600 design/product operation configuration."""
    project = project_root.expanduser().resolve()
    design_id = _identifier(design_id, "design ID")
    product_profile_id = _identifier(product_profile_id, "product profile ID")
    version = _version_label(version_number)
    if art_template_mode not in ART_TEMPLATE_MODES:
        raise OperationConfigError(
            f"art template mode must be one of {', '.join(ART_TEMPLATE_MODES)}"
        )
    if name_mode not in NAME_MODES:
        raise OperationConfigError(f"name mode must be one of {', '.join(NAME_MODES)}")
    if upscale_backend not in UPSCALE_BACKENDS:
        raise OperationConfigError(
            f"upscale backend must be one of {', '.join(UPSCALE_BACKENDS)}"
        )
    if isinstance(pet_name_max_length, bool) or not 1 <= pet_name_max_length <= 64:
        raise OperationConfigError("pet name max length must be between 1 and 64")
    pet_name = pet_name.strip()
    if name_mode != "none" and not pet_name:
        raise OperationConfigError(f"pet name is required for name mode {name_mode!r}")
    if name_mode == "none":
        pet_name = ""
    art_model = art_model or DEFAULT_MODELS.get(art_provider, "")
    pet_model = pet_model or DEFAULT_MODELS.get(pet_provider, "")
    try:
        validate_generation_quality(
            provider=art_provider, model=art_model, quality=art_quality
        )
        validate_generation_quality(
            provider=pet_provider, model=pet_model, quality=pet_quality
        )
    except ValueError as exc:
        raise OperationConfigError(str(exc)) from exc
    if not project.is_dir():
        raise OperationConfigError(f"project root is not a directory: {project}")
    target = (
        project
        / "work"
        / "configs"
        / f"{design_id}--{product_profile_id}--{version}.env"
    ).resolve()
    (project / "work" / "design-inputs" / design_id).mkdir(
        parents=True, exist_ok=True
    )
    return _write_private_config(
        target,
        _design_template(
            output=target,
            project_root=project,
            design_id=design_id,
            product_profile_id=product_profile_id,
            art_template_mode=art_template_mode,
            art_provider=art_provider,
            art_model=art_model,
            art_quality=art_quality,
            pet_provider=pet_provider,
            pet_model=pet_model,
            pet_quality=pet_quality,
            name_mode=name_mode,
            pet_name=pet_name,
            pet_name_max_length=pet_name_max_length,
            upscale_backend=upscale_backend,
        ),
        force=force,
    )
